trigger:
- develop

variables:
  buildConfiguration: 'Release'
  targetPool: avanadepool

pool: $(targetPool)

steps:
- script: dotnet restore
  displayName: Ripristino dei pacchetti NuGet
  enabled: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build della soluzione completa
  enabled: true